### ISSUE TITLE
The sound coming out is corrupted

### ISSUE THREAD

**Issue by ramaswag** [biner88/metronome#13] opened 2024-07-11 12:33 UTC
The sound is very very noisy and you can't almost hear the original sound. The problem is for sure not the sample, as it is clean and also if I change the file I get the same result.

**Comment by biner88** [comment] 2024-07-14 06:00
Are you using the sound file from the example?

**Comment by ramaswag** [comment] 2024-07-14 06:40
No

**Comment by biner88** [comment] 2024-07-14 06:45
Sound files are specially processed. You can refer to the file parameters in the example to re-edit your file.

**Comment by ramaswag** [comment] 2024-07-14 07:42
Ahh ok I see, thanks 🙏

**Comment by biner88** [comment] 2024-08-01 04:03
@manudicri  Is the same true for examples?

**Comment by manudicri** [comment] 2024-08-10 18:12
Hi @biner88 
I haven't tried yet. Anyway, I think you can reopen this issue since the problem is there on Android. Just like the video I attached.
My audio file is a .WAV, 44,1khz 32bit. I got to try with other audio files as soon as I can.

Thanks
Manu

**Comment by biner88** [comment] 2024-08-11 13:53
You can try the audio file provided by the sample, I tested it fine on multiple Android devices. You can upload your audio file here and I'll test it.

**Comment by manudicri** [comment] 2024-09-02 23:18
Hi, 
I noticed that the .wav file in the sample repository has its 'encoding' field set to 'Microsoft PCM', whereas my .wav file is encoded as 'Microsoft IEEE'. This seems to be causing issues when playing the file on Android. I converted the file to PCM encoding, which resolved the issue in the Android simulator. 
I will test it on a real device and update you on the results.

Thank you
Manu

**Comment by manudicri** [comment] 2024-09-24 23:11
Working fine. 
You can close this ticket. 
Thank you

**Closed** 2024-10-21 07:52 UTC
